# This is a basic workflow to help you get started with Actions

name: Command Macos

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build and run 
        run: | 
          brew install boost
          ver=`ls /usr/local/Cellar/boost/`
          echo Boost version $ver
          
          git clone https://github.com/JGCRI/hector.git
          cd ./hector
          
          BOOST=/usr/local/Cellar/boost
          
          echo listing what is in boostlib
          ls $BOOST/$ver/lib
          
          echo listing what is in boost root
          ls $BOOST/$ver/include/boost
          
 
          # Build the Hector executable 
          #BOOSTLIB=/usr/local/lib   BOOSTVERSION=$ver   BOOSTROOT=/usr/include/boost make hector
          # Run a Hector ini  
          #./src/hector ./inst/input/hector_rcp45.ini
          ## Run the Hector test script 
          # bash ./test_hector.sh ./src/hector
